### ISSUE TITLE
Document minimal AWS role/permissions to use cloud scanner

### ISSUE THREAD

**Issue by demeringo** [Boavizta/cloud-scanner#147]
## Problem

Document minimal AWS role/permissions to use cloud scanner

**Comment by demeringo** [comment]
Todo: verify if the role set in serverless.yml https://github.com/Boavizta/cloud-scanner/blob/aacffd0314828c10483615eb0918e18848e7bd87/serverless.yml#L11 is not too permissive, not sure we need the describe alarms...

```yml
iam:
    role:
      statements:
        - Effect: Allow
          Action: "ec2:DescribeInstances"
          Resource: "*"
        - Effect: Allow
          Action: "cloudwatch:GetMetricStatistics"
          Resource: "*"
        - Effect: Allow
          Action: "cloudwatch:DescribeAlarm"
          Resource: "*"
```
