### ISSUE TITLE
Publish docker image to a public registry

### ISSUE THREAD

**Issue by demeringo** [Boavizta/cloud-scanner#24]
## Problem

Docker image is currently build in CI and available only on the private registry of this project.
Cannot be retrieved without authentication / proper permission which make deployment difficult in Enterprise context.

## Solution

Publish the image to docker registry.

_Not sure if Boavizta org has account / credentials setup for docker registry._

**Comment by demeringo** [comment]
@da-ekchajzer @bpetit or @samuelrince do you know if Boavizta has an account on docker registry ?
 Something we could use in CI to authenticate and publish a _public_ docker image.

**Comment by da-ekchajzer** [comment]
@demeringo we use github registery 

## To login : 

### During a GitHub workflow
``` yml
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
```


### In CLI
```
docker login ghcr.io --username github-account
```

## To tag & push :

``` bash
docker tag ghcr.io/boavizta/toto:latest 
docker push ghcr.io/boavizta/toto:latest 
```
