### ISSUE TITLE
Use feature flag in lambda http

### ISSUE THREAD

**Issue by demeringo** [Boavizta/cloud-scanner#89]
## Problem

Reduce compile time

## Solution

We only deploy using REST API gateway, so we can make use of lambda_http feature flags https://github.com/awslabs/aws-lambda-rust-runtime#feature-flags-in-lambda_http

```toml
[dependencies.lambda_http]
version = "0.6"
default-features = false
features = ["apigw_rest"]
```
